version: '3'
services:
  db-hottest100:
    image: postgres
    volumes:
      - ./tmp:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
  hottest100:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '3000:3000'
    command: bash -c "npm install && npm start"